### ISSUE TITLE
nodejs mongodb

### ISSUE THREAD

**Issue by junrdev** [learning-zone/nodejs-basics#63]
<h4> can i do a directory on <em>nodejs-mongodb</em> </h4>
<p>will include some mongodb interaction with the node js runtime</p>
<p>i will do it on a separate branch and the maintainers will get to review the code before publishing</p>

<code>i will be grateful for your response</code>

**Comment by learning-zone** [comment]
Yes, please.

**Comment by junrdev** [comment]
Right away
